language: go
sudo: false

go:
  - 1.7
  - 1.8
  - tip

os:
  - linux
  - osx

notifications:
  email:
    - ackleymi@gmail.com

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - make vendor
script:
  - make test
